-- Schema des Moduls `auth_password`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS auth_password;

-- =============================================================================================
-- auth_password
-- =============================================================================================

-- No identifier of its own: the account's EMAIL anchor identifies it.
CREATE TABLE auth_password.enrollment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
