-- Schema des Moduls `auth_password`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS auth_password;

-- =============================================================================================
-- auth_password
-- =============================================================================================

-- No identifier of its own: the account's EMAIL anchor identifies it.
CREATE TABLE auth_password.enrollment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE auth_password.enroll_tool_session (
    tool_session_id UUID PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_enroll_tool_session_created_at ON auth_password.enroll_tool_session (created_at);

CREATE TABLE auth_password.auth_tool_session (
    tool_session_id     UUID PRIMARY KEY,
    enrollment_ref_id   VARCHAR(255),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_tool_session_created_at ON auth_password.auth_tool_session (created_at);

CREATE TABLE auth_password.lookup_tool_session (
    tool_session_id UUID PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_lookup_tool_session_created_at ON auth_password.lookup_tool_session (created_at);
