-- =============================================================================================
-- KOBIL: Geraetebindung ueber einen externen Dienstleister
--
-- Zwei Schemata, weil es zwei Parteien sind:
--   auth_kobil  - unser Tool-Modul: was unser Backend ueber die Bindung weiss.
--   kobil  - das simulierte Fremdsystem: was KOBIL selbst haelt. Nie direkt gelesen,
--                 nur ueber die KobilSsms-Schnittstelle (docs/06-ablaeufe.md).
-- =============================================================================================

CREATE SCHEMA IF NOT EXISTS auth_kobil;

-- ---------------------------------------------------------------------------------------------
-- auth_kobil
-- ---------------------------------------------------------------------------------------------

-- Das Credential ist die KOBIL-Aktivierung eines Telefons. Anders als bei auth_device liegt der
-- Schluessel nicht bei uns: wir halten die Kennung, mit der sich eine eingeloeste Assertion
-- vergleichen laesst, und den PIN, den dieses Backend fuer das Geraet verwahrt.
CREATE TABLE auth_kobil.enrollment (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kobil_tenant_id    VARCHAR(64)  NOT NULL,
    kobil_user_id      VARCHAR(128) NOT NULL,
    -- Die Geraetekennung: Vergleichsanker nach der Einloesung. Kein Angebotsfilter, denn beim
    -- Angebot kennt der Server sie noch nicht (siehe binding_key_ref).
    kobil_device_id    VARCHAR(255) NOT NULL,
    -- Demo-only: Klartext, nicht verschluesselt. Er muss herausgegeben werden koennen, also
    -- kommt kein Hash in Frage (ADR-22). Damit steht er auch in der offenen H2-Konsole.
    pin                VARCHAR(32)  NOT NULL,
    -- Serverseitige Haelfte des lokal biometriegeschuetzten Secrets, gehasht. NULL heisst: der
    -- Nutzer hat dem Biometrie-Weg nicht zugestimmt. Kein Flag daneben.
    unlock_secret_hash VARCHAR(255),
    -- Der DPoP-Schluessel des einrichtenden Kanals: der Filter, der beim Angebot greift
    -- (ToolDescriptor.keyBinding).
    binding_key_ref    VARCHAR(64)  NOT NULL,
    label              VARCHAR(100),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ux_kobil_enrollment_user UNIQUE (kobil_user_id)
);
CREATE INDEX ix_kobil_enrollment_device ON auth_kobil.enrollment (kobil_device_id);

CREATE TABLE auth_kobil.enroll_tool_session (
    tool_session_id    UUID PRIMARY KEY,
    kobil_tenant_id    VARCHAR(64)  NOT NULL,
    kobil_user_id      VARCHAR(128) NOT NULL,
    activation_code    VARCHAR(128) NOT NULL,
    pin                VARCHAR(32)  NOT NULL,
    -- Waehrend der Einrichtung im Klartext, damit ein Reload den Ablauf nicht abschneidet. Beim
    -- Abschluss bleibt nur der Hash, und nur mit Zustimmung (auth_kobil.enrollment.unlock_secret_hash).
    unlock_secret      VARCHAR(255) NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_kobil_enroll_tool_session_created_at ON auth_kobil.enroll_tool_session (created_at);

CREATE TABLE auth_kobil.auth_tool_session (
    tool_session_id        UUID PRIMARY KEY,
    enrollment_ref_id      VARCHAR(255),
    -- NULL = noch nicht freigegeben. Gesetzt traegt die Spalte zugleich das Zugangsmittel
    -- (pin | biometric), das der spaetere Completed als amr meldet: ein Feld, kein Flag daneben.
    user_verification      VARCHAR(16),
    pin_release_expires_at TIMESTAMP WITH TIME ZONE,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_kobil_auth_tool_session_created_at ON auth_kobil.auth_tool_session (created_at);

-- ---------------------------------------------------------------------------------------------
-- kobil (Fremdsystem)
-- ---------------------------------------------------------------------------------------------
