-- Was eine Kontoloeschung ueberlebt (ADR-39): ein append-only Protokoll, dass und wie etwas
-- geschah, nie was. Keine Attributwerte, keine Stammdaten, keine Dokumentnummer (§ 20 PAuswG).
-- Feste Spalten fuer das, was jedes Ereignis hat; details (JSON) fuer den Rest, die Schluessel
-- legt ChangeLog fest. Bewusst ohne Fremdschluessel auf account.account, damit die Zeilen die
-- Loeschung ueberleben.
CREATE TABLE account.change_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT       NOT NULL,
    change_type  VARCHAR(32)  NOT NULL,
    subject     VARCHAR(50),
    acr         VARCHAR(16),
    details     JSON,
    -- Suchschluessel, je eine indizierte Spalte statt einer Suche im JSON: danach wird eine Person
    -- Jahre spaeter unter Millionen Zeilen gefunden. Nur bei IDENTIFIED gesetzt.
    lookup_key  VARCHAR(64),
    person_id   VARCHAR(64),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_change_log_type CHECK (change_type IN (
        'IDENTIFIED', 'ATTRIBUTE_RETRACTED', 'METHOD_ADDED', 'METHOD_DEACTIVATED', 'ACCOUNT_DELETED', 'ACCOUNT_ABSORBED'))
);
CREATE INDEX ix_change_log_account ON account.change_log (account_id, occurred_at);
-- Die Frage der Aufbewahrung: welche Konten sind seit wann geloescht?
CREATE INDEX ix_change_log_type_time ON account.change_log (change_type, occurred_at);
-- Die Suche nach einer Person (PersonLookupKey bzw. Registernummer), auch nach der Loeschung.
CREATE INDEX ix_change_log_lookup_key ON account.change_log (lookup_key);
CREATE INDEX ix_change_log_person_id ON account.change_log (person_id);
