-- Schema des Moduls `account`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS account;

-- =============================================================================================
-- account
-- =============================================================================================

CREATE TABLE account.account (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version    BIGINT NOT NULL DEFAULT 0
);

-- The one current, normalized value per (account, anchor attribute) - the only resolve-identity
-- and uniqueness authority for it. AccountProfile.personId/email/emailConfirmedAt read from here.
CREATE TABLE account.anchor (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       BIGINT       NOT NULL,
    attribute_type   VARCHAR(50)  NOT NULL,
    normalized_value VARCHAR(255) NOT NULL,
    -- What was proven when this value was bound, capped like account.auth_method.enrolled_under_acr
    -- (ADR-5), never the level a tool merely claims.
    established_acr  VARCHAR(16),
    established_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ux_anchor_account_type UNIQUE (account_id, attribute_type),
    CONSTRAINT ux_anchor_value UNIQUE (attribute_type, normalized_value),
    CONSTRAINT fk_anchor_account FOREIGN KEY (account_id) REFERENCES account.account (id) ON DELETE CASCADE
);

-- Append-only claim log: every attribute value ever asserted, with its source and level.
-- auth_method_id names the method instance whose enrollment established the claim, so revoking
-- that method can retract exactly what it asserted; NULL for claims from identification tools,
-- which produce no credential at all.
CREATE TABLE account.claim (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       BIGINT       NOT NULL,
    attribute_type   VARCHAR(50)  NOT NULL,
    claim_value      VARCHAR(255) NOT NULL,
    normalized_value VARCHAR(255) NOT NULL,
    claim_source     VARCHAR(50)  NOT NULL,
    established_acr  VARCHAR(16),
    auth_method_id   UUID,
    established_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_claim_account FOREIGN KEY (account_id) REFERENCES account.account (id) ON DELETE CASCADE
);
CREATE INDEX ix_claim_account_id ON account.claim (account_id);
-- "What did this method instance ever assert?" - the retraction path's only query.
CREATE INDEX ix_claim_auth_method_id ON account.claim (auth_method_id);

-- A withdrawn value (ADR-12), its own row rather than a flag, so the claim log never mutates. It
-- carries provenance like an assertion: who withdrew it (claim_source), why and when. An anchor
-- whose value is retracted is deleted, because account.anchor is projection, not log.
CREATE TABLE account.retraction (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       BIGINT       NOT NULL,
    attribute_type   VARCHAR(50)  NOT NULL,
    normalized_value VARCHAR(255) NOT NULL,
    claim_source     VARCHAR(32)  NOT NULL,
    reason           VARCHAR(255),
    retracted_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_retraction_account FOREIGN KEY (account_id) REFERENCES account.account (id) ON DELETE CASCADE
);
-- The anti-join shape of findEstablished: the account first, then the (type, value) pair the
-- subtraction matches on.
CREATE INDEX ix_retraction_account_type_value ON account.retraction (account_id, attribute_type, normalized_value);

-- One registered method instance. (enrollment_type, enrollment_id) points at the credential row in
-- the owning method module; deactivated rows stay, so deletion still finds every credential.
CREATE TABLE account.auth_method (
    id                 UUID         PRIMARY KEY,
    account_id         BIGINT       NOT NULL,
    method             VARCHAR(50)  NOT NULL,
    enrollment_type    VARCHAR(50)  NOT NULL,
    enrollment_id      VARCHAR(255) NOT NULL,
    active             BOOLEAN      NOT NULL,
    enrolled_under_acr VARCHAR(16),
    label              VARCHAR(100),
    details            JSON,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    deactivated_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_auth_method_deactivation CHECK (active = (deactivated_at IS NULL)),
    CONSTRAINT fk_auth_method_account FOREIGN KEY (account_id) REFERENCES account.account (id) ON DELETE CASCADE
);
CREATE INDEX ix_auth_method_account_id ON account.auth_method (account_id, method);
-- Reverse direction: credential -> accounts (revocation sweeps, orphan checks per method module).
CREATE INDEX ix_auth_method_enrollment ON account.auth_method (enrollment_type, enrollment_id);
