-- Schema des Moduls `personenverzeichnis`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS personenverzeichnis;

-- =============================================================================================
-- personenverzeichnis: mock of the external person register
-- =============================================================================================

CREATE TABLE personenverzeichnis.person (
    -- Partnernummer: 'P' and nine digits, handed out by the register (ADR-34) - the person id every
    -- other module knows (account anchor PERSON_ID), not a technical counter.
    id           VARCHAR(10)  PRIMARY KEY,
    -- Role (ADR-34): Versicherter = versnr set; Partner = only the Partnernummer. A KVNR only exists for an insured
    -- person (ck_person_kvnr_nur_versichert), but may be missing for a while - it changes now and then.
    kvnr         VARCHAR(20),
    -- Versicherungsnummer: only for a person insured with us, eight digits, unique when set.
    versnr       VARCHAR(8),
    name         VARCHAR(255),
    vorname      VARCHAR(255),
    geburtsdatum DATE,
    strasse      VARCHAR(255),
    hausnummer   VARCHAR(20),
    plz          VARCHAR(10),
    ort          VARCHAR(255),
    -- Contact details: the demo pre-fills forms from them; no account keeps or follows them.
    email        VARCHAR(255),
    mobilnummer  VARCHAR(30),
    CONSTRAINT ux_person_kvnr UNIQUE (kvnr),
    CONSTRAINT ux_person_versnr UNIQUE (versnr),
    CONSTRAINT ck_person_kvnr_nur_versichert CHECK (kvnr IS NULL OR versnr IS NOT NULL)
);

-- A Freischaltcode belongs to the register, not to the ident tool that checks it (ADR-31): the
-- register issues it, the ident tool only asks whether a given one is valid. Only the digest lives
-- here - what ident_fsc compares against.
CREATE TABLE personenverzeichnis.freischaltcode (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id  VARCHAR(10) NOT NULL,
    code_hash  VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_freischaltcode_person FOREIGN KEY (person_id) REFERENCES personenverzeichnis.person (id) ON DELETE CASCADE
);
CREATE INDEX ix_freischaltcode_person_id_code_hash ON personenverzeichnis.freischaltcode (person_id, code_hash);

-- The simulated letter that carries a Freischaltcode to the person. The plaintext exists only here,
-- as it does in the real world on paper (demo frame, like ADR-22) - the demo reads it back from the
-- "mailbox" instead of keeping a second hard-coded list of codes.
CREATE TABLE personenverzeichnis.brief (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id          VARCHAR(10) NOT NULL,
    freischaltcode_id  BIGINT      NOT NULL,
    code               VARCHAR(64) NOT NULL,
    versandt_am        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_brief_person FOREIGN KEY (person_id) REFERENCES personenverzeichnis.person (id) ON DELETE CASCADE,
    CONSTRAINT fk_brief_freischaltcode FOREIGN KEY (freischaltcode_id) REFERENCES personenverzeichnis.freischaltcode (id) ON DELETE CASCADE
);
CREATE INDEX ix_brief_person_id ON personenverzeichnis.brief (person_id);
