-- Schema des Moduls `auth_device`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS auth_device;

-- =============================================================================================
-- auth_device
-- =============================================================================================

-- The credential is the public half of a non-extractable device key pair.
CREATE TABLE auth_device.enrollment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kty        VARCHAR(10)  NOT NULL,
    crv        VARCHAR(10)  NOT NULL,
    x          VARCHAR(255) NOT NULL,
    y          VARCHAR(255) NOT NULL,
    thumbprint VARCHAR(64)  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ux_enrollment_thumbprint UNIQUE (thumbprint)
);

CREATE TABLE auth_device.enroll_tool_session (
    tool_session_id UUID PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_enroll_tool_session_created_at ON auth_device.enroll_tool_session (created_at);

CREATE TABLE auth_device.auth_tool_session (
    tool_session_id     UUID PRIMARY KEY,
    enrollment_ref_id   VARCHAR(255),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_tool_session_created_at ON auth_device.auth_tool_session (created_at);
