-- Schema des Moduls `auth_qr`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS auth_qr;

-- =============================================================================================
-- auth_qr
-- =============================================================================================

-- Pure opt-in marker ("this account allows QR login"), no secret.
CREATE TABLE auth_qr.enrollment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Connects a WEB auth-qr activation to an APP confirm-qr-login decision. pairing_code is the
-- lookup capability; verification_code is only compared by eye.
CREATE TABLE auth_qr.login_request (
    pairing_code         VARCHAR(16) PRIMARY KEY,
    verification_code    VARCHAR(8)  NOT NULL,
    expected_account_id  BIGINT,
    status               VARCHAR(32) NOT NULL,
    resolving_account_id BIGINT,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at           TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_login_request_expires_at ON auth_qr.login_request (expires_at);

CREATE TABLE auth_qr.enroll_tool_session (
    tool_session_id UUID PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_enroll_tool_session_created_at ON auth_qr.enroll_tool_session (created_at);

CREATE TABLE auth_qr.auth_tool_session (
    tool_session_id UUID PRIMARY KEY,
    pairing_code    VARCHAR(16) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_tool_session_created_at ON auth_qr.auth_tool_session (created_at);

CREATE TABLE auth_qr.lookup_tool_session (
    tool_session_id UUID PRIMARY KEY,
    pairing_code    VARCHAR(16) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_lookup_tool_session_created_at ON auth_qr.lookup_tool_session (created_at);

CREATE TABLE auth_qr.confirm_tool_session (
    tool_session_id UUID PRIMARY KEY,
    pairing_code    VARCHAR(16),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_confirm_tool_session_created_at ON auth_qr.confirm_tool_session (created_at);
