// Shared by the explainer video (build.mjs) and the narration of the demo video (e2e-video/narrator.ts).
// Pronunciation hints for the voice: applied to the spoken text only, the subtitles keep the real spelling.
export const SPOKEN = [
  [/\bDPoP\b/g, 'D-Pop'],
  [/Keycloak-Update/g, 'Kieklohk-Äppdeet'],
  [/App-Update/g, 'Äpp-Äppdeet'],
  [/Keycloak/g, 'Kieklohk'],
  [/\bApp(s?)\b/g, 'Äpp$1'],
  [/Journey-Trace/g, 'Dschörni-Trehs'],
  [/Journey-Diagramme/g, 'Dschörni-Diagramme'],
  [/\bJourneys\b/g, 'Dschörnis'],
  [/\bJourney\b/g, 'Dschörni'],
  [/\bTrace\b/g, 'Trehs'],
  [/Tool-Endpunkte/g, 'Tuhl-Endpunkte'],
  [/\bTools?\b/g, (m) => (m === 'Tools' ? 'Tuhls' : 'Tuhl')],
  [/Access-Token/g, 'Äxess-Tohken'],
  [/\bTokens\b/g, 'Tohkens'],
  // espeak reads a leading "st" as "scht" whatever the spelling: the sentences say it without the word.
  [/startet einen Step-up/g, 'verlangt einen weiteren Nachweis'],
  [/folgt ein Step-up/g, 'folgt ein weiterer Nachweis'],
  [/\bWebsite\b/g, 'Websaid'],
  // The same for "Spring": the slide names it, the sentence leaves it out.
  [/Spring-Boot-Modulith/g, 'Modulith'],
  [/Kotlin/g, 'Kottlinn'],
  [/React-Frontend/g, 'Riäkt-Front-Änd'],
  [/Frontends/g, 'Front-Änds'],
  [/Backend-Kern/g, 'Bäck-Änd-Kern'],
  [/\bBackend\b/g, 'Bäck-Änd'],
  [/\bPolicy\b/g, 'Pollissi'],
  [/\bNect\b/g, 'Neckt'],
  [/\bKOBIL\b/g, 'Kobil'],
  [/QR-Code/g, 'Kuh-Er-Code'],
  [/\bdomain\b/g, 'Do-mehn'],
  [/frameworkfrei/g, 'ohne Frehmwörk'],
  [/hardwaregestützten/g, 'Haadwär-gestützten'],
  [/\bBuild\b/g, 'Bild'],
  [/Smartphone/g, 'Smartfohn'],
  [/Sicherheitsaudit/g, 'Sicherheits-Ohdditt'],
  [/Sicherheitsniveaus/g, 'Sicherheitsniwohs'],
  [/\bNiveaus\b/g, 'Niwohs'],
  [/Beispiel-Story/g, 'Beispielgeschichte'],
  [/„next“/g, 'Next'],
  [/\bIdentity Demo\b/g, 'Ei-Dentiti Demo'],
  [/Admin-Seite/g, 'Äddminn-Seite'],
  [/\bHash\b/g, 'Häsch'],
  [/\bPIN\b/g, 'Pin'],
  [/\bloa(\d)\b/g, 'Niveau $1'],
  [/\bErika\b/g, 'Ehrika'],
]

/** The text as the voice should read it. */
export const spoken = (text) => SPOKEN.reduce((s, [re, r]) => s.replace(re, r), text)
