-- Schema des Moduls `auth_sms`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS auth_sms;

-- =============================================================================================
-- auth_sms
-- =============================================================================================

-- Exists only after a successful TAN check, so it is confirmed by definition.
CREATE TABLE auth_sms.enrollment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(32) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE auth_sms.enroll_tool_session (
    tool_session_id UUID PRIMARY KEY,
    phone_number    VARCHAR(32),
    issued_tan_hash VARCHAR(64),
    tan_expires_at  TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_enroll_tool_session_created_at ON auth_sms.enroll_tool_session (created_at);

CREATE TABLE auth_sms.auth_tool_session (
    tool_session_id     UUID PRIMARY KEY,
    enrollment_ref_id   VARCHAR(255),
    issued_tan_hash     VARCHAR(64),
    tan_expires_at      TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_tool_session_created_at ON auth_sms.auth_tool_session (created_at);

-- account_id is only known after the first PATCH resolved it.
CREATE TABLE auth_sms.lookup_tool_session (
    tool_session_id UUID PRIMARY KEY,
    account_id      BIGINT,
    issued_tan_hash VARCHAR(64),
    tan_expires_at  TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_lookup_tool_session_created_at ON auth_sms.lookup_tool_session (created_at);
