-- Schema des Moduls `auth_sms`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS auth_sms;

-- =============================================================================================
-- auth_sms
-- =============================================================================================

-- Exists only after a successful TAN check, so it is confirmed by definition.
CREATE TABLE auth_sms.enrollment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(32) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
